name: Prettier & ESLint

on:
  push:
    branches:
      - main

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pwa

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Format
      run: bun run format

    - name: Lint
      run: bun run lint
